title: Pedro Kroger
email: kroger@pedrokroger.net
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://pedrokroger.net"
twitter_username: pedrokroger1
github_username:  kroger

kramdown:
  input: GFM

toc:
  min_level: 1
  max_level: 2
  list_class: "nav flex-column nav-toc"
  item_class: nav-item

plugins:
  - jekyll-feed
  - jekyll-toc

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - assets/main.scss
  - old
