title: "Teste"
email: kroger@pedrokroger.net
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://pedrokroger.net"
twitter_username: pedrokroger1
github_username:  kroger

toc:
  max_level: 2
  list_class: "nav flex-column toc"
  item_class: nav-item
#  item_prefix: item- # Default: "toc-":

theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - assets/main.scss
